---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-website
  name: example-website
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: example-website
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        deployment: example-website
    spec:
      volumes:
      - name: htdocs
        persistentVolumeClaim:
          claimName: pvc-htdocs
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: website-files
        persistentVolumeClaim:
          claimName: pvc-website-files
      containers:
      - image: golden-image-example/nginx:1.22
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: htdocs
          mountPath: "/var/www/html/"
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: website-files
          mountPath: /var/www/html/htdocs/sites/default/
      - image: golden-image-example/php:8.2-fqm
        imagePullPolicy: Always
        name: php
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: htdocs
          mountPath: "/var/www/html/"
        - name: website-files
          mountPath: /var/www/html/htdocs/sites/default/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30