---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-website
  name: nginx
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: example-website
  sessionAffinity: None
  type: ClusterIP