---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-htdocs
  labels:
    app: htdocs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-website-files
  labels:
    app: htdocs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi