---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php
  name: php
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: php
  strategy:
    # rollingUpdate:
    #  maxSurge: 25%
    #  maxUnavailable: 25%
    # type: RollingUpdate
    type: Recreate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        deployment: php
    spec:
      volumes:
      - name: htdocs
        persistentVolumeClaim:
          claimName: pvc-htdocs-php
      containers:
      - image: php:8.2-fqm
        imagePullPolicy: Always
        name: php
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: htdocs
          mountPath: "/var/www/html/"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30